apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-server-override-cm
  namespace:  devtroncd
data:
  override: |
    apiVersion: apps/v1
    kind: NatsCluster
    metadata:
      name: devtron-nats
    update:
      spec:
        size: 3
        template:
          spec 
            containers:
            - resources:
                limits: 
                  cpu: 0.1
                  memory: 40Mi
                requests:
                  cpu: 0.05
                  memory: 20Mi